### ISSUE TITLE
Make post description limited to 50-300 characters of plain text

### ISSUE THREAD

**Issue by justaniles** [justaniles/catilyfe#12]
According to this [Moz article](https://moz.com/learn/seo/meta-description), html meta description tags should be between 50-300 characters and only contain plain text. 

Since le deux will use the post description to set the meta description tag on each post's page, the metadata description should follow these rules.

This limitation should be enforced in both Deux Moto's edit post page and in CatiCake. So @petersulucz get on this

**Comment by petersulucz** [comment]
The description is already limited to 256 characters
