### ISSUE TITLE
Gracefully handle network errors in all views

### ISSUE THREAD

**Issue by justaniles** [justaniles/catilyfe#2]
After flying with a wonderfully spotty internet connection, it's become apparent that most CL pages currently do not have any error views (most just look like they're forever loading if a network error occurs). This must change.

Places that need error views:
- [ ] Home page
- [ ] Single post view
- [ ] Admin home page

**Comment by petersulucz** [comment]
Also, needs to support curveball error messages, designed to keep users on their toes

**Comment by justaniles** [comment]
Probably should just create a single error page, into which any error message can be passed and printed. Also must feature sad cati.

EDIT: Looks like I already talked about this in another issue #8. Man am I on top of it

**Comment by justaniles** [comment]
Closing as duplicate
